version: "3"
services:
  database:
    image: "mysql:8.0"
    environment:
      MYSQL_DATABASE: prodyna
      MYSQL_PASSWORD: 4567
      MYSQL_ROOT_PASSWORD: 4567
    ports:
      - "3308:3306"
  app:
    image: "marko991/reserve-your-spot_app:0.0.14-SNAPSHOT"
    ports:
      - "8080:8080"
    restart: unless-stopped
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://database:3306/prodyna?autoReconnect=true&useSSL=false
      SPRING_DATASOURCE_USERNAME: "root"
      SPRING_DATASOURCE_PASSWORD: "4567"
    depends_on:
      - database

