version: "3"
services:
  database:
    image: "mysql:8.0"
    environment:
      MYSQL_DATABASE: prodyna
      MYSQL_PASSWORD: 4567
      MYSQL_ROOT_PASSWORD: 4567
    ports:
      - "3307:3306"
  app:
    depends_on:
      - database
    build: ./
    restart: on-failure
    ports:
      - "8080:8080"
    environment:
      SPRING_APPLICATION_JSON: '{
          "spring.datasource.url"  : "jdbc:mysql://database:3306/prodyna?allowPublicKeyRetrieval=true&useSSL=false",
          "spring.datasource.username" : "root",
          "spring.datasource.password" : "4567",
          "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL8Dialect",
          "spring.jpa.hibernate.ddl-auto" : "create-drop"
        }'


