name: Create docker image and push to DockerHub

on:
  push:
    branches: [ "master" ]
    
jobs:

  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Run Gradle task
      run: gradle docker
