# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ "master" ]

jobs:
  build_app:
    name: Build App
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Build with Gradle
        run: gradle build -x test
      - name: Docker login
        run : docker login --username marko991 --password B1389!piki22#09
      - name: Build Docker image with latest tag
        run: docker build . --file Dockerfile --tag marko991/reserve-your-spot:latest
      - name: Publish dockerimage to docker hub
        run: docker push marko991/reserve-your-spot:latest
